/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: CentureMorrals (https://sketchfab.com/CentureMorrals)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/heart-f72840dd96584883b2edc80bccbf187b
Title: Heart
*/

import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'
import heartGlb from './assets/heart.glb'
import { MeshPhysicalMaterial, Group, Object3DEventMap } from 'three'
import { forwardRef } from 'react'

export const Heart = forwardRef<Group<Object3DEventMap>>(
  (props: GroupProps, ref) => {
    const { nodes, materials } = useGLTF(heartGlb)
    return (
      <group {...props} ref={ref} dispose={null}>
        <group scale={0.0045}>
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cube__0 as any).geometry}
            material={new MeshPhysicalMaterial({ color: 0xbe185d })}
            // material={materials['Scene_-_Root']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 24.457, 100]}
          />
        </group>
      </group>
    )
  }
)

useGLTF.preload(heartGlb)
